rootProject.name = "dittnav-meta-repo"

includeBuild("dittnav")
includeBuild("dittnav-api")
includeBuild("dittnav-common-lib")
includeBuild("dittnav-legacy-api")
includeBuild("dittnav-dependencies")
includeBuild("dittnav-event-handler")
includeBuild("dittnav-eventer-modia")
includeBuild("dittnav-docker-compose")
includeBuild("brukernotifikasjon-docs")
includeBuild("dittnav-varsel-bestiller")
includeBuild("dittnav-event-aggregator")
includeBuild("brukernotifikasjon-schemas")
includeBuild("dittnav-event-test-producer")
includeBuild("brukernotifikasjon-topic-iac")
includeBuild("dittnav-periodic-metrics-reporter")
includeBuild("dittnav-brukernotifikasjoner-intro")
includeBuild("dittnav-nightly-usage-statistics-reporter")
